basePath: /v2
definitions:
  favorite.FavoriteProduct:
    properties:
      description:
        type: string
      disability:
        type: boolean
      id:
        type: integer
      image_url:
        type: string
      name:
        type: string
      price:
        type: integer
      remain:
        type: integer
    type: object
  member.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  member.MemberInfo:
    properties:
      address:
        $ref: '#/definitions/sql.NullString'
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      payment_id:
        $ref: '#/definitions/sql.NullInt64'
      phone_num:
        $ref: '#/definitions/sql.NullString'
      shipment_id:
        $ref: '#/definitions/sql.NullInt64'
      username:
        type: string
    type: object
  member.RegistrationRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - name
    - password
    - username
    type: object
  product.CreationRequest:
    properties:
      description:
        type: string
      disability:
        type: boolean
      image_url:
        $ref: '#/definitions/sql.NullString'
      name:
        type: string
      price:
        type: integer
      remain:
        type: integer
      tags:
        items:
          type: integer
        type: array
      vendor_id:
        type: integer
    required:
    - description
    - disability
    - name
    - price
    - remain
    - tags
    - vendor_id
    type: object
  product.Product:
    properties:
      build_time:
        type: string
      description:
        type: string
      disability:
        type: boolean
      id:
        type: integer
      image_url:
        $ref: '#/definitions/sql.NullString'
      name:
        type: string
      price:
        type: integer
      remain:
        type: integer
      tags:
        items:
          type: integer
        type: array
      vendor_id:
        type: integer
    required:
    - description
    - disability
    - name
    - price
    - remain
    - vendor_id
    type: object
  product.UpdateRequest:
    properties:
      description:
        type: string
      disability:
        type: boolean
      id:
        type: integer
      image_url:
        $ref: '#/definitions/sql.NullString'
      name:
        type: string
      price:
        type: integer
      remain:
        type: integer
      tags:
        items:
          type: integer
        type: array
    required:
    - description
    - disability
    - id
    - name
    - price
    - remain
    - tags
    type: object
  sql.NullInt64:
    properties:
      int64:
        type: integer
      valid:
        description: Valid is true if Int64 is not NULL
        type: boolean
    type: object
  sql.NullString:
    properties:
      string:
        type: string
      valid:
        description: Valid is true if String is not NULL
        type: boolean
    type: object
  tag.Tag:
    properties:
      id:
        type: integer
      name:
        type: string
      type:
        description: '0: product, 1: vendor'
        type: integer
    required:
    - name
    - type
    type: object
host: localhost:8080
info:
  contact:
    email: ericncnl3742@gmail.com
    name: API Support
    url: https://github.com/NTUT-Database-System-Course/ACW-Backend/issues
  description: This is an API server for ACW-Backend
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: ACW-Backend API
  version: 0.0.1
paths:
  /api/favorite/add:
    post:
      consumes:
      - application/json
      description: Add a product to the user's favorite list
      parameters:
      - description: Product ID
        in: query
        name: product_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Add favorite
      tags:
      - favorite
  /api/favorite/delete:
    delete:
      consumes:
      - application/json
      description: Remove a product from the user's favorite list
      parameters:
      - description: Product ID
        in: query
        name: product_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Delete favorite
      tags:
      - favorite
  /api/favorite/list:
    get:
      consumes:
      - application/json
      description: List the user's favorite products
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/favorite.FavoriteProduct'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: List favorites
      tags:
      - favorite
  /api/member/info:
    get:
      consumes:
      - application/json
      description: Get member info
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/member.MemberInfo'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Get member info
      tags:
      - member
  /api/member/login:
    post:
      consumes:
      - application/json
      description: Login member
      parameters:
      - description: Login Request
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/member.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login member
      tags:
      - member
  /api/member/register:
    post:
      consumes:
      - application/json
      description: Register member
      parameters:
      - description: Member Registration
        in: body
        name: member
        required: true
        schema:
          $ref: '#/definitions/member.RegistrationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: Conflict
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register member
      tags:
      - member
  /api/product/create:
    post:
      consumes:
      - application/json
      description: Create a new product
      parameters:
      - description: Create Product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/product.CreationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Create product
      tags:
      - product
  /api/product/list:
    get:
      consumes:
      - application/json
      description: Get all products
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/product.Product'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List products
      tags:
      - product
  /api/product/update:
    put:
      consumes:
      - application/json
      description: Update an existing product
      parameters:
      - description: Update Product
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/product.UpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Update product
      tags:
      - product
  /api/tag/list:
    get:
      consumes:
      - application/json
      description: List all tags
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/tag.Tag'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List all tags
      tags:
      - tag
swagger: "2.0"
