basePath: /api/v1
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /users/{id}:
    get:
      consumes:
      - application/json
      description: 根據用戶ID獲取用戶資料
      parameters:
      - description: 用戶ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 獲取用戶資料
      tags:
      - 用戶
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
