basePath: /v2
definitions:
  member.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  member.MemberInfo:
    properties:
      address:
        $ref: '#/definitions/sql.NullString'
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      payment_id:
        $ref: '#/definitions/sql.NullInt64'
      phone_num:
        $ref: '#/definitions/sql.NullString'
      shipment_id:
        $ref: '#/definitions/sql.NullInt64'
      username:
        type: string
    type: object
  member.RegistrationRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - name
    - password
    - username
    type: object
  sql.NullInt64:
    properties:
      int64:
        type: integer
      valid:
        description: Valid is true if Int64 is not NULL
        type: boolean
    type: object
  sql.NullString:
    properties:
      string:
        type: string
      valid:
        description: Valid is true if String is not NULL
        type: boolean
    type: object
host: localhost:8080
info:
  contact:
    email: ericncnl3742@gmail.com
    name: API Support
    url: https://github.com/NTUT-Database-System-Course/ACW-Backend/issues
  description: This is an API server for ACW-Backend
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: ACW-Backend API
  version: 0.0.1
paths:
  /api/member/info:
    get:
      consumes:
      - application/json
      description: Get member info
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/member.MemberInfo'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get member info
      tags:
      - member
  /api/member/login:
    post:
      consumes:
      - application/json
      description: Login member
      parameters:
      - description: Login Request
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/member.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login member
      tags:
      - member
  /api/member/register:
    post:
      consumes:
      - application/json
      description: Register member
      parameters:
      - description: Member Registration
        in: body
        name: member
        required: true
        schema:
          $ref: '#/definitions/member.RegistrationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register member
      tags:
      - member
swagger: "2.0"
