definitions:
  other.Msg:
    properties:
      msg:
        type: string
    type: object
info:
  contact:
    email: chenshiang@onon1101.org
    name: API Support
    url: https://github.com/NTUT-Database-System-Course/ACW-Backend/issues
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /api/hello:
    get:
      consumes:
      - application/json
      description: Print welcome
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/other.Msg'
      summary: Get Welcom
      tags:
      - User
swagger: "2.0"
