basePath: /v2
definitions:
  users.User:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: chenshiang@onon1101.org
    name: API Support
    url: https://github.com/NTUT-Database-System-Course/ACW-Backend/issues
  description: This is an API server for ACW-Backend
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: ACW-Backend API
  version: 0.0.1
paths:
  /api/users/info:
    get:
      consumes:
      - application/json
      description: Get user info
      parameters:
      - description: User ID
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/users.User'
            type: array
      summary: Get user info
      tags:
      - users
swagger: "2.0"
